title: Stimhack

author:
  name: Stimhack
  email: run@stimhack.sh

description: >

favicon: favicon.png

theme: stimhack

show_excerpts: false

highlighter: rouge

plugins:
 - jekyll-feed
 - jekyll-seo-tag

permalink: /:title.html
