title: Stimhack
author:
  name: Stimhack
  email: run@stimhack.sh
description: >

show_excerpts: false

theme: stimhack
favicon: favicon.png

plugins:
 - jekyll-feed
 - jekyll-seo-tag

permalink: /:title.html
